#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSC Smart Seva - Go-Live Deployment Guide (Body PDF, ReportLab)
Cover is generated separately via HTML/Playwright and merged with pypdf.
"""
import os, sys, hashlib

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                PageBreak, KeepTogether)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Fonts (allowed set only) ━━
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#eeedec')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#edeceb')
HEADER_FILL   = colors.HexColor('#645939')
COVER_BLOCK   = colors.HexColor('#766b4a')
BORDER        = colors.HexColor('#dad5c5')
ICON          = colors.HexColor('#93824e')
ACCENT        = colors.HexColor('#94761e')
ACCENT_2      = colors.HexColor('#53aecc')
TEXT_PRIMARY  = colors.HexColor('#1b1b19')
TEXT_MUTED    = colors.HexColor('#7c7972')
SEM_SUCCESS   = colors.HexColor('#408256')
SEM_WARNING   = colors.HexColor('#997e49')
SEM_ERROR     = colors.HexColor('#924b44')
SEM_INFO      = colors.HexColor('#4775a3')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

OUT = '/home/z/my-project/scripts/golive-body.pdf'

# ━━ Page geometry ━━
MARGIN = 0.9 * inch
AVAIL = A4[0] - 2 * MARGIN  # ~465pt

# ━━ Styles ━━
S = {}
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif-Bold', fontSize=20, leading=26,
                         textColor=HEADER_FILL, spaceBefore=18, spaceAfter=10)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif-Bold', fontSize=14, leading=20,
                         textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                           textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
S['bullet'] = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=16,
                             textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                             leftIndent=16, bulletIndent=4, spaceAfter=5)
S['code'] = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8.5, leading=13,
                           textColor=TEXT_PRIMARY, alignment=TA_LEFT,
                           backColor=SECTION_BG, borderColor=BORDER, borderWidth=0.6,
                           borderPadding=(6, 8, 6, 8), leftIndent=6, rightIndent=6,
                           spaceBefore=6, spaceAfter=10)
S['quote'] = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5, leading=16,
                            textColor=TEXT_PRIMARY, leftIndent=24, spaceBefore=6, spaceAfter=10,
                            borderColor=ACCENT, borderWidth=0, borderPadding=0)
S['cap'] = ParagraphStyle('Cap', fontName='FreeSerif', fontSize=9, leading=13,
                          textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=4, spaceAfter=10)
S['th'] = ParagraphStyle('TH', fontName='FreeSerif-Bold', fontSize=9.5, leading=13,
                         textColor=colors.white, alignment=TA_LEFT)
S['td'] = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.5, leading=13.5,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['tdc'] = ParagraphStyle('TDC', fontName='FreeSerif', fontSize=9.5, leading=13.5,
                          textColor=TEXT_PRIMARY, alignment=TA_CENTER)
S['tdmono'] = ParagraphStyle('TDM', fontName='DejaVuSans', fontSize=8.5, leading=13,
                             textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['toc0'] = ParagraphStyle('TOC0', fontName='FreeSerif-Bold', fontSize=11, leading=20,
                           textColor=TEXT_PRIMARY, leftIndent=0)
S['toc1'] = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10, leading=17,
                           textColor=TEXT_MUTED, leftIndent=16)

def P(text, style='body'):
    return Paragraph(text, S[style])

def bullet(text):
    return Paragraph(text, S['bullet'], bulletText='\u2022')

def callout(title, text, kind='info'):
    box_colors = {'info': SEM_INFO, 'warn': SEM_WARNING, 'danger': SEM_ERROR, 'ok': SEM_SUCCESS}
    c = box_colors.get(kind, SEM_INFO)
    inner = Table(
        [[Paragraph(f'<b>{title}</b>', ParagraphStyle('ct', fontName='FreeSerif-Bold',
                                                      fontSize=10, leading=14, textColor=c)),
          ],
         [Paragraph(text, ParagraphStyle('cb', fontName='FreeSerif', fontSize=9.8,
                                         leading=14.5, textColor=TEXT_PRIMARY))]],
        colWidths=[AVAIL - 20])
    inner.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f7f6f4')),
        ('LINEBEFORE', (0, 0), (0, -1), 3, c),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
    ]))
    wrap = Table([[inner]], colWidths=[AVAIL], hAlign='CENTER')
    wrap.setStyle(TableStyle([('LEFTPADDING', (0, 0), (-1, -1), 10),
                              ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                              ('TOPPADDING', (0, 0), (-1, -1), 4),
                              ('BOTTOMPADDING', (0, 0), (-1, -1), 6)]))
    return wrap

def make_table(header, rows, ratios, mono_cols=None, caption=None):
    mono_cols = mono_cols or []
    col_widths = [r * AVAIL for r in ratios]
    data = [[Paragraph(f'<b>{h}</b>', S['th']) for h in header]]
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            st = 'tdmono' if i in mono_cols else 'td'
            cells.append(Paragraph(str(cell), S[st]))
        data.append(cells)
    t = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 10), t]
    if caption:
        out += [Paragraph(caption, S['cap'])]
    out += [Spacer(1, 8)]
    return out

def heading(text, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    style = S['h1'] if level == 0 else S['h2']
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text.replace('<b>', '').replace('</b>', '')
    p.bookmark_key = key
    return p

# ━━ TOC Doc Template ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('FreeSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, A4[1] - 0.55 * inch, 'CSC Smart Seva - Go-Live Deployment Guide')
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, A4[1] - 0.62 * inch, A4[0] - MARGIN, A4[1] - 0.62 * inch)
    canvas.line(MARGIN, 0.62 * inch, A4[0] - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 8)
    canvas.drawString(MARGIN, 0.45 * inch, 'Version 1.0 - September 2026')
    canvas.drawRightString(A4[0] - MARGIN, 0.45 * inch, f'Page {doc.page}')
    canvas.restoreState()

doc = TocDocTemplate(OUT, pagesize=A4,
                     leftMargin=MARGIN, rightMargin=MARGIN,
                     topMargin=0.95 * inch, bottomMargin=0.85 * inch,
                     title='CSC Smart Seva - Go-Live Deployment Guide',
                     author='Z.ai')

story = []

# ━━ TOC page ━━
toc = TableOfContents()
toc.levelStyles = [S['toc0'], S['toc1']]
story.append(Paragraph('Table of Contents', S['h1']))
story.append(Spacer(1, 8))
story.append(toc)
story.append(PageBreak())

# ============================================================
# Chapter 1: System Overview
# ============================================================
story.append(heading('1. System Overview - Kya Ready Hai'))
story.append(P(
    'CSC Smart Seva ek WhatsApp-based digital seva automation system hai jo aapke customers ko '
    '14 sarkari services WhatsApp chat ke through deta hai. System abhi tak fully built aur tested '
    'hai: 25 n8n workflows, 22 database tables, ek admin portal, aur complete backup files. '
    'Ye guide step-by-step batati hai ki ise production mein live kaise karein - server se lekar '
    'WhatsApp production aur live payments tak.'))
story.append(P(
    'Abhi system sandbox mein MOCK mode par chal raha hai. Iska matlab hai ki WhatsApp messages '
    'aur payments dono simulate ho rahe hain, lekin poora logic - intent detection, field '
    'validation, document collection, payment verification, receipts aur operator tasks - real '
    'hai. Live karne ke liye sirf 4 cheezein badalni hain: ek server, ek domain, Meta WhatsApp '
    'production credentials aur Razorpay live keys.'))

story.append(heading('1.1 Current Assets', 1))
story += make_table(
    ['Asset', 'Detail', 'Status'],
    [
        ['n8n Workflows', '25 workflows (CSC 01-25), hub-and-spoke architecture', 'Built + tested'],
        ['Data Tables', '22 tables, 237+ seed rows (fields, docs, pricing, config)', 'Populated'],
        ['Admin Portal', 'Next.js dashboard - applications, tasks, payments, settings', 'Built + verified'],
        ['Supabase Backup', 'workflows-backup.json, datatables-backup.json, credentials', 'Ready'],
        ['Migration Scripts', 'import-datatables.js + activation scripts', 'Ready'],
        ['Operator Guide', 'CSC_Services_Operator_Guide.pdf (14 services)', 'Delivered'],
    ],
    [0.22, 0.56, 0.22], caption='Table 1: Ready assets inventory')
story.append(P(
    'Sabse important baat: services ke beech koi hardcoding nahi hai. Har service ka fields, '
    'documents aur pricing database tables (service_engine config) se aata hai. Isliye aap portal '
    'se pricing change kar sakte ho, naya field add kar sakte ho, aur workflow ko touch karne ki '
    'zaroorat nahi padti. Yehi design production mein aapko sabse zyada time bachayega.'))

story.append(heading('1.2 Live Architecture (Target)', 1))
story.append(P(
    'Live hone par system aise chalega: Customer ka WhatsApp message Meta Cloud API se aapke '
    'server par bane n8n webhook par aayega. n8n intent samjhega, fields collect karega, '
    'documents lega, aur payment link banayega. Payment confirm hone par application finalize '
    'hoti hai, receipt jaata hai, operator task banta hai aur admin portal mein dikhne lagta hai. '
    'Operator portal se approve karta hai aur certificate deliver hota hai. Saara data Supabase '
    'Postgres mein rehta hai jo n8n aur portal dono share karte hain.'))
story += make_table(
    ['Component', 'Role', 'Hosting Target'],
    [
        ['Meta WhatsApp Cloud API', 'Message receive/send (official channel)', 'Meta cloud (free)'],
        ['n8n (25 workflows)', 'Bot brain - conversation, validation, payments', 'India VPS (Docker/bun)'],
        ['Supabase Postgres', 'Single source of truth - 22 tables', 'Supabase cloud'],
        ['Admin Portal (Next.js)', 'Applications, tasks, services, settings manage', 'Same VPS (PM2) / Vercel'],
        ['Razorpay', 'UPI/cards collection + webhook verification', 'Razorpay cloud'],
    ],
    [0.28, 0.42, 0.30], caption='Table 2: Production architecture components')

# ============================================================
# Chapter 2: Go-Live Roadmap
# ============================================================
story.append(heading('2. Go-Live Roadmap - 8 Steps'))
story.append(P(
    'Poora launch 3-5 din ka kaam hai, agar Meta business verification fast ho jaye. Neeche wala '
    'roadmap follow karein - sequence important hai kyunki har step previous step par depend '
    'karta hai. Sabse pehle server aur database ready karein, phir domain lagayen, uske baad '
    'WhatsApp webhook register hoga (HTTPS zaroori hai), aur last mein live payments on honge.'))
story += make_table(
    ['Step', 'Kaam', 'Time', 'Dependency'],
    [
        ['1', 'VPS server kharidna aur n8n install karna', '2-3 ghante', '-'],
        ['2', 'Supabase Postgres setup + data restore', '1-2 ghante', 'Step 1'],
        ['3', 'Domain + HTTPS (nginx + SSL)', '1 ghanta', 'Step 1'],
        ['4', 'Workflows import + activate + DB switch', '2 ghante', 'Step 2, 3'],
        ['5', 'Meta WhatsApp production credentials', '1-3 din (verification)', 'Step 3'],
        ['6', 'Razorpay live keys + webhook', '2-4 ghante', 'Step 3'],
        ['7', 'Admin portal deploy + password change', '1 ghanta', 'Step 2'],
        ['8', 'End-to-end testing + soft launch', '1 din', 'Sab steps'],
    ],
    [0.08, 0.47, 0.22, 0.23], caption='Table 3: Go-live sequence with time estimates')
story.append(callout('Golden Rule',
    'Kabhi bhi seedha live par switch na karein. Pehle TEST mode mein 10-15 real applications '
    'chalayen (apne number se), phir PAYMENT_MODE aur WhatsApp credentials live karein. '
    'Soft launch strategy: pehle 20 trusted customers, phir full public.', 'ok'))

story.append(heading('2.1 Monthly Cost Estimate', 1))
story += make_table(
    ['Item', 'Option A (Budget)', 'Option B (Recommended)'],
    [
        ['VPS 2GB RAM', 'Hostinger/DO Bangalore: Rs 400-700/mo', 'DO Bangalore 2GB: Rs 800/mo'],
        ['Supabase', 'Free tier (500MB, enough for start)', 'Pro Rs 1,500/mo (jab data badhe)'],
        ['Domain .in/.com', 'Rs 100-800/year', 'Rs 800/year'],
        ['WhatsApp Cloud API', 'Free (1000 service convos/mo)', 'Free + usage-based after limit'],
        ['Razorpay', '2% per transaction (UPI 0%)', 'Same'],
        ['n8n license', 'Self-host free (Community)', 'Self-host free'],
        ['Approx total', 'Rs 500-700/month', 'Rs 900-1,200/month'],
    ],
    [0.24, 0.38, 0.38], caption='Table 4: Estimated monthly running cost (INR)')
story.append(P(
    'Shuruat mein Option A kaafi hai. 500 applications per month tak free Supabase tier '
    'comfortably chalega. WhatsApp Cloud API ka pricing conversation-based hai - customer-initiated '
    'service conversations (24-hour window) ke first 1,000 per month free hain, jo ek naye CSC ke '
    'liye kaafi se kaafi zyada hai. Baad mein jab volume badhega, Meta ka per-conversation charge '
    'lagbhag Rs 0.30-0.80 aata hai.'))

# ============================================================
# Chapter 3: Server Setup
# ============================================================
story.append(heading('3. Server Setup - VPS India'))
story.append(P(
    'Server ke liye India region choose karna zaroori hai kyunki WhatsApp aur government portals '
    'dono ka latency India se best rehta hai, aur Razorpay webhooks bhi fastest yahin aate hain. '
    'DigitalOcean Bangalore, AWS Mumbai, ya Hostinger India - teeno theek hain. Minimum 2GB RAM '
    'chahiye kyunki n8n ko workflows chalane ke liye memory chahiye aur Next.js portal bhi wahi '
    'chalega. Ubuntu 22.04 LTS LTS image select karein aur SSH key setup karke login karein.'))

story.append(heading('3.1 Base Installation', 1))
story.append(P(
    'SSH login ke baad ye commands ek-ek karke chalayen. Ye Node.js 20, bun runtime, n8n, nginx '
    'aur PM2 install karega - poora stack ek hi server par:'))
story.append(P('apt update &amp;&amp; apt upgrade -y', 'code'))
story.append(P('curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &amp;&amp; apt install -y nodejs nginx', 'code'))
story.append(P('npm install -g bun pm2', 'code'))
story.append(P('mkdir -p /opt/csc &amp;&amp; cd /opt/csc &amp;&amp; bun install n8n@latest', 'code'))
story.append(P(
    'n8n ko bun se install karna intentionally kiya gaya hai - pichle testing mein npm se install '
    'par n8n OOM (out of memory) hota tha jab 25 workflows ek saath active the, jabki bun runtime '
    'memory efficiently handle karta hai. n8n version 2.40.7 verified hai hamare workflows ke '
    'saath, to bilkul naya version aane par bhi pehle staging mein test karein.'))

story.append(heading('3.2 systemd Service (Auto-Start)', 1))
story.append(P(
    'Server reboot hone par n8n khud start hona chahiye. Iske liye systemd service banayen:'))
story.append(P('nano /etc/systemd/system/n8n.service', 'code'))
story.append(P(
    '[Unit] Description=n8n CSC | After=network.target<br/>'
    '[Service] Type=simple | User=root | WorkingDirectory=/opt/csc<br/>'
    'Environment=N8N_HOST=csc.yourdomain.in<br/>'
    'Environment=N8N_PORT=5678 | Environment=N8N_PROTOCOL=https<br/>'
    'Environment=WEBHOOK_URL=https://csc.yourdomain.in/<br/>'
    'Environment=GENERIC_TIMEZONE=Asia/Kolkata | Environment=TZ=Asia/Kolkata<br/>'
    'Environment=DB_TYPE=postgresdb<br/>'
    'Environment=DB_POSTGRESDB_HOST=aws-0-ap-south-1.pooler.supabase.com<br/>'
    'Environment=DB_POSTGRESDB_DATABASE=postgres | Environment=DB_POSTGRESDB_PORT=5432<br/>'
    'Environment=DB_POSTGRESDB_USER=postgres.xxx | Environment=DB_POSTGRESDB_PASSWORD=xxxx<br/>'
    'ExecStart=/usr/local/bin/bun x n8n start<br/>'
    'Restart=always | RestartSec=5<br/>'
    '[Install] WantedBy=multi-user.target', 'code'))
story.append(P('systemctl daemon-reload &amp;&amp; systemctl enable n8n &amp;&amp; systemctl start n8n', 'code'))
story.append(callout('Timezone Important',
    'GENERIC_TIMEZONE=Asia/Kolkata aur TZ dono set karein. Reminder system (CSC 21) ke quiet '
    'hours (21:00 se 09:00) aur daily admin digest (CSC 23) ke schedules isi timezone se '
    'calculate hote hain. Galat timezone par reminders raat ko 2 baje jayenge.', 'warn'))

# ============================================================
# Chapter 4: Database Migration
# ============================================================
story.append(heading('4. Database - Supabase Postgres Migration'))
story.append(P(
    'Abhi sandbox mein n8n apna data SQLite file mein rakhta hai. Production mein SQLite theek '
    'nahi hai - backup mushkil, concurrent writes slow, aur portal share nahi kar sakta. Supabase '
    'Postgres pe se hi hamara target tha isliye migration files already ready hain. Supabase '
    'account banakar naya project create karein (region: ap-south-1 Mumbai), aur Project Settings '
    'se connection string copy karein.'))

story.append(heading('4.1 Restore Steps', 1))
story.append(P(
    'Migration folder (download/supabase-migration/) ke saare files server par /opt/csc/migration/ '
    'mein copy karein. Phir ye order follow karein:'))
story.append(bullet('<b>Step A:</b> n8n ko pehli baar DB_TYPE=postgresdb ke saath start karein - ye automatically saare n8n internal tables bana dega.'))
story.append(bullet('<b>Step B:</b> node import-datatables.js chalayen - ye 22 CSC tables (applications, service_fields, service_documents, service_pricing, system_config etc.) Supabase public schema mein banayega aur 237+ seed rows daalega.'))
story.append(bullet('<b>Step C:</b> n8n UI (Settings &gt; Data Tables) mein confirm karein ki tables dikh rahe hain.'))
story.append(bullet('<b>Step D:</b> workflows-backup.json import karein - n8n UI se (Import from File) ya CLI se: n8n import:workflow --input=workflows-backup.json'))
story.append(bullet('<b>Step E:</b> Credentials manually re-enter karein (WhatsApp token, Razorpay keys) - security ke liye credentials backup encrypted hai.'))
story.append(bullet('<b>Step F:</b> Sab 25 workflows activate karein. Import ke baad workflows deactivated hote hain - ye n8n ka known behaviour hai. Ek-ek karke UI se toggle karein ya official API use karein.'))
story.append(callout('Activation Pitfall',
    'SQLite me directly active=1 set karne se kaam NAHI chalta - n8n cache follow karta hai. '
    'Official REST API use karein: POST /api/v1/workflows/{id}/activate with header '
    'X-N8N-API-KEY. Isi se activation guaranteed hoti hai. Activate-all script '
    'scripts/phase-build/activate-all.sh me ready hai.', 'danger'))

story.append(heading('4.2 Verify Migration', 1))
story.append(P(
    'Migration ke baad ye 3 checks karein. Pehla: n8n UI mein koi bhi workflow open karke Data '
    'Table node dekhein - usme service_fields table dikhna chahiye. Doosra: Supabase SQL Editor '
    'mein SELECT COUNT(*) FROM service_catalog chalayen - 16 rows aani chahiye. Teesra: system_config '
    'table mein PAYMENT_MODE=MOCK abhi bhi hona chahiye (live switch baad mein hoga).'))
story += make_table(
    ['Check', 'Expected Result'],
    [
        ['SELECT COUNT(*) FROM service_catalog', '16'],
        ['SELECT COUNT(*) FROM service_fields', '99'],
        ['SELECT COUNT(*) FROM service_documents', '54'],
        ['SELECT config_value FROM system_config WHERE config_key = \'APP_NUMBER_PREFIX\'', 'CSC-2026-'],
        ['n8n workflows active', '25 of 25'],
    ],
    [0.62, 0.38], mono_cols=[0], caption='Table 5: Post-migration verification queries')

# ============================================================
# Chapter 5: Domain + HTTPS
# ============================================================
story.append(heading('5. Domain + HTTPS Setup'))
story.append(P(
    'Meta WhatsApp Cloud API webhook ke liye HTTPS URL mandatory hai - HTTP par webhook register '
    'nahi hota. Isliye ek domain kharidna (GoDaddy/Namecheap/Hostinger se .in ya .com) aur usse '
    'VPS ke IP par point karna pehla infrastructure kaam hai. DNS A record mein @ aur dono '
    'subdomains add karein: bot.yourdomain.in (n8n webhook) aur admin.yourdomain.in (portal).'))
story.append(P(
    'DNS propagate hone ke baad (15-30 minute) nginx reverse proxy setup karein. nginx port 80/443 '
    'par sunta hai aur traffic internally n8n (port 5678) aur portal (port 3000) mein baant deta hai:'))
story.append(P(
    'server { listen 80; server_name bot.yourdomain.in;<br/>'
    'location / { proxy_pass http://localhost:5678;<br/>'
    'proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;<br/>'
    'proxy_set_header X-Forwarded-Proto https; } }', 'code'))
story.append(P(
    'apt install certbot python3-certbot-nginx<br/>'
    'certbot --nginx -d bot.yourdomain.in -d admin.yourdomain.in', 'code'))
story.append(P(
    'Certbot automatically Let\'s Encrypt SSL certificate laga dega aur HTTP ko HTTPS par redirect '
    'kar dega. Certificate 90 din ka hota hai aur certbot renewal cron khud set karta hai. '
    'Ek baar https://bot.yourdomain.in/healthz open karke confirm karein ki n8n ka response aa raha hai.'))

# ============================================================
# Chapter 6: WhatsApp Production
# ============================================================
story.append(heading('6. WhatsApp Production (Meta WABA)'))
story.append(P(
    'Ye sabse important aur sabse time-taking step hai kyunki Meta ki business verification mein '
    '1-3 din lag sakte hain. SandBox se production jaane ke liye ye cheezein chahiye: Meta '
    'Business Portfolio, ek verified business, WhatsApp Business Account (WABA), aur ek phone '
    'number jo WhatsApp par registered NAHI ho (na app mein, na kisi aur account mein). Number '
    'naya kharidna best hai - purana number agar personal WhatsApp par hai to pehle usse delete '
    'karna hoga.'))

story.append(heading('6.1 Meta Setup Checklist', 1))
story += make_table(
    ['Step', 'Action', 'Note'],
    [
        ['1', 'developers.facebook.com par app banayein (type: Business)', 'Free'],
        ['2', 'WhatsApp product add karein + WABA create karein', 'Auto'],
        ['3', 'Business verification documents submit karein', '1-3 din'],
        ['4', 'Phone number register karein (display name approve karayein)', 'Rental/new SIM'],
        ['5', 'System User banakar permanent token generate karein', 'Never expiring'],
        ['6', 'phone_number_id + waba_id copy karein', 'App dashboard'],
        ['7', 'Webhook subscribe karein + verify token set karein', 'messages field ON'],
    ],
    [0.08, 0.52, 0.40], caption='Table 6: Meta WhatsApp production setup sequence')

story.append(heading('6.2 Credentials Portal Mein Dalna', 1))
story.append(P(
    'Token milne ke baad Admin Portal &gt; Settings &gt; WhatsApp Cloud API section mein ye 4 '
    'values bharein (ya seedhe Supabase system_config table mein update karein). n8n har message '
    'par fresh config padhta hai, isliye restart ki zaroorat nahi:'))
story += make_table(
    ['Config Key', 'Kya Bharna Hai', 'Example'],
    [
        ['WHATSAPP_PHONE_NUMBER_ID', 'Meta dashboard se phone number ID', '123456789012345'],
        ['WHATSAPP_ACCESS_TOKEN', 'System User permanent token', 'EAAG...long-string'],
        ['WHATSAPP_API_VERSION', 'Graph API version', 'v21.0'],
        ['ADMIN_WHATSAPP_NUMBER', 'Aapka operator WhatsApp (91 prefix)', '9198XXXXXX99'],
    ],
    [0.34, 0.42, 0.24], mono_cols=[0, 2], caption='Table 7: WhatsApp system_config values')
story.append(P(
    'Webhook URL Meta app dashboard mein yeh dalein: https://bot.yourdomain.in/webhook/csc-router '
    'Verify token field mein koi bhi string dein (system mein csc_verify_2026 set hai) aur '
    'messages webhook field subscribe karein. Jab bhi customer message bhejega, Meta usse is '
    'URL par POST karega aur CSC 01 router workflow usse process karega.'))

story.append(heading('6.3 24-Hour Window aur Templates', 1))
story.append(P(
    'WhatsApp ka sabse bada rule: aap customer ko sirf 24-hour window ke andar free-form message '
    'bhej sakte ho - window tab khulti hai jab customer ne aapko message kiya ho. Hamara poora '
    'bot flow customer-initiated hai isliye yahan koi problem nahi aayegi. Lekin reminders (CSC '
    '21) customer-initiated window ke bahar ja sakte hain - payment reminder bhejne ke liye '
    'approved message template use karna padega. Meta dashboard se 3 templates banayein:'))
story.append(bullet('<b>payment_reminder:</b> "Namaste {{1}}, aapki {{2}} application pending hai. Payment complete karne ke liye: {{3}}"'))
story.append(bullet('<b>status_update:</b> "Aapki application {{1}} ka status: {{2}}. Detail ke liye reply karein."'))
story.append(bullet('<b>certificate_ready:</b> "Badhai ho {{1}}! Aapka {{2}} ready hai. Download: {{3}}"'))
story.append(callout('Quality Rating',
    'Naye numbers par Meta "Limited Access" (250 unique customers/day) deta hai. 30 din tak '
    'achha quality rating maintain karne par limit badhti hai. Spam na karein - REMINDER_MAX_PER_APP=3 '
    'config already har application par maximum 3 reminders limit karta hai.', 'warn'))

# ============================================================
# Chapter 7: Razorpay Live
# ============================================================
story.append(heading('7. Razorpay Live Payments'))
story.append(P(
    'Payments live karne ke liye Razorpay dashboard se activation complete karein: business KYC '
    '(PAN, GST ya Shop Act, bank account) submit karein. Approval ke baad dashboard ke Live Mode '
    'tab se Key ID aur Key Secret milenge. Phir Admin Portal Settings mein ye karein:'))
story += make_table(
    ['Config Key', 'Value', 'Kahan Se'],
    [
        ['PAYMENT_MODE', 'RAZORPAY_LIVE', 'Manual (MOCK se change karein)'],
        ['RAZORPAY_KEY_ID', 'rzp_live_xxxxxxxx', 'Dashboard - API Keys'],
        ['RAZORPAY_KEY_SECRET', '(secret string)', 'Dashboard - API Keys (ek baar dikhta hai)'],
        ['RAZORPAY_WEBHOOK_SECRET', 'csc_webhook_secret_2026', 'Same rakhna hai - workflows isi se verify karte hain'],
    ],
    [0.30, 0.28, 0.42], mono_cols=[0, 1], caption='Table 8: Payment config keys')
story.append(P(
    'Razorpay dashboard mein webhook bhi register karein: URL https://bot.yourdomain.in/webhook/'
    'csc-payment-callback, event payment.captured, aur secret csc_webhook_secret_2026. CSC 12 '
    'workflow har webhook par HMAC-SHA256 signature verify karta hai - galat secret wale fake '
    'requests reject ho jayengi. Ye security layer already built aur tested hai (demo mein '
    'CSC-2026-EAUM1N application isi flow se PAID hui thi).'))
story.append(callout('Go-Live Test Pattern',
    'Live keys dalne ke baad pehla test apne hi number se karein: poora PAN flow complete karein '
    'aur Rs 1 test product par real UPI payment karein. Confirm karein ki (1) Razorpay dashboard '
    'mein payment dikhe, (2) application status PAID ho, (3) receipt WhatsApp par aaye, (4) '
    'operator task bane. Sab 4 pass hone par hi public launch karein.', 'ok'))

# ============================================================
# Chapter 8: Admin Portal Deployment
# ============================================================
story.append(heading('8. Admin Portal Deployment'))
story.append(P(
    'Admin portal Next.js application hai jo aapko sab kuch ek jagah manage karne deti hai: '
    'applications (form data, documents, status timeline), operator tasks (approve/reject), 16 '
    'services ki config (fields, documents, pricing), payments ledger, live conversations aur '
    'system settings. Portal Supabase Postgres se directly connect hota hai - wahi database jo '
    'n8n use karta hai. Isliye dono ka data hamesha synced rehta hai.'))
story.append(P(
    'Portal deploy karne ke 2 options hain. Option A (recommended): wahi VPS jahan n8n chal raha '
    'hai - extra cost nahi. Option B: Vercel pe free hosting - easy but DATABASE_URL public '
    'internet se Supabase ko hit karti hai (SSL enforced hai to safe hai). Option A ke steps:'))
story.append(bullet('Portal folder /opt/csc/portal/ mein copy karein (ya git clone karein).'))
story.append(bullet('.env file banayein: DATABASE_URL (Supabase pooler URL), ADMIN_PASSWORD (strong password), PORTAL_SECRET (random 32 chars).'))
story.append(bullet('bun install &amp;&amp; npx prisma generate &amp;&amp; bun run build chalayen.'))
story.append(bullet('pm2 start npm --name csc-portal -- run start (port 3000) chalayen.'))
story.append(bullet('nginx mein admin.yourdomain.in server block add karein (proxy_pass http://localhost:3000).'))
story.append(callout('First Login',
    'Portal ka default password csc-admin-2026 hai (sirf pehli login ke liye). Login ke turant '
    'baad .env me ADMIN_PASSWORD change karke pm2 restart csc-portal chalayen. Production me '
    'default password kabhi na chhodein.', 'danger'))
story.append(P(
    'Portal ke andar saara data n8n ke saath same tables se aata hai. Operator jab task approve '
    'karta hai to portal application_status_history aur audit_log mein entry likhta hai - yaani '
    'poora audit trail preserved rehta hai. Application status flow portal mein is tarah manage '
    'hota hai: DRAFT &gt; SUBMITTED &gt; PAID &gt; IN_PROGRESS &gt; APPROVED &gt; DELIVERED '
    '(REJECTED bhi kahin se bhi possible hai).'))

# ============================================================
# Chapter 9: Pre-Launch Checklist
# ============================================================
story.append(heading('9. Pre-Launch Checklist'))
story.append(P(
    'Public launch se pehle neeche wale 12 tests sequentially pass karne zaroori hain. Har test '
    'ek real scenario simulate karta hai. Inme se koi bhi fail ho to launch postpone karein aur '
    'fix karein - customer ke saamne broken bot brand image kharab karta hai.'))
story += make_table(
    ['#', 'Test', 'Expected'],
    [
        ['1', 'Naye number se "hi" message', 'Welcome + services list aaye'],
        ['2', '"PAN card banwana hai" bolo', 'Service confirm + price dikhaye (Rs 166)'],
        ['3', 'Galat phone number type karo (5 digit)', 'Validation error message aaye'],
        ['4', 'Saare 7 fields + 3 documents bhejo', 'Payment link aaye'],
        ['5', 'Payment link se UPI payment karo', 'Receipt + confirmation aaye'],
        ['6', 'Razorpay dashboard check karo', 'Payment captured dikhe'],
        ['7', 'Portal &gt; Applications kholo', 'Nayi application PAID status par dikhe'],
        ['8', 'Portal &gt; Tasks me approve karo', 'Status APPROVED ho + history bane'],
        ['9', '"status" message customer se', 'Bot approved status bataye'],
        ['10', 'Payment ke bina 30 min wait karo', 'Reminder aaye (max 3, quiet hours respect)'],
        ['11', 'Admin number par daily digest', 'Roz summary aaye'],
        ['12', 'Unknown/galat message ("asdfgh")', 'Bot gracefully help bataye, crash na ho'],
    ],
    [0.07, 0.45, 0.48], caption='Table 9: 12-point pre-launch test suite')
story.append(P(
    'Test 10 ke liye note karein: reminder turant nahi aata - CSC 21 har ghante check karta hai '
    'ki kaunsi applications 24 ghante se pending hain, aur unme se qualified par reminder bhejta '
    'hai. Testing ke waqt REMINDER_MAX_PER_APP ko temporarily 1 rakh sakte ho taaki spam na ho.'))

# ============================================================
# Chapter 10: Maintenance & Monitoring
# ============================================================
story.append(heading('10. Maintenance & Monitoring'))
story.append(P(
    'Live hone ke baad daily 10 minute ka routine kaafi hai. Subah portal kholke dekhein: kal '
    'kitni applications aayi, kitni PAID hui, pending tasks kitne hain. Conversations page par '
    'wo customers dekhein jinke state PAYMENT ya DOCS par atke hain - unhe manually reminder '
    'bhejna (ya portal se status change karna) chahiye. Weekly ek baar Payments page se Razorpay '
    'dashboard reconcile karein - total collected match hona chahiye.'))

story.append(heading('10.1 Daily & Weekly Routine', 1))
story += make_table(
    ['Frequency', 'Task', 'Kahan'],
    [
        ['Daily subah', 'Pending tasks approve/reject karo', 'Portal - Operator Tasks'],
        ['Daily subah', 'Atki conversations dekho', 'Portal - Conversations'],
        ['Daily', 'n8n executions me errors check karo', 'n8n UI - Executions (Status=Error)'],
        ['Weekly', 'Payments reconcile (Razorpay vs Portal)', 'Portal - Payments'],
        ['Weekly', 'Server disk + memory check karo', 'SSH: df -h, free -m'],
        ['Monthly', 'Supabase backup download karo', 'Supabase - Backups'],
        ['Monthly', 'WhatsApp quality rating dekho', 'Meta Business Manager'],
    ],
    [0.20, 0.50, 0.30], caption='Table 10: Maintenance routine')

story.append(heading('10.2 Backup Strategy', 1))
story.append(P(
    'Teen layers ki backup rakhein. Pehla: Supabase ka built-in daily backup (Pro plan mein '
    'automatic, free tier mein manual download). Doosra: har hafte n8n ka export - workflows ko '
    'n8n CLI se export karke ya UI se download karke ek folder mein rakhein (aaj ke backup files '
    'already isi format mein hain). Teesra: system_config aur service config ka snapshot - portal '
    'ke Settings page se JSON copy karke store karein. Server crash ho jaaye to 2-3 ghante mein '
    'poora system naye VPS par restore ho jayega.'))
story.append(P(
    'Ek aur cheez: workflows ko edit karne se pehle hamesha pehle export karke backup lein. '
    '25 workflows ka hub-and-spoke design hai - koi bhi workflow change karte waqt uske callers '
    'ka dhyan rakhein (CSC 20 sender sab use karte hain, CSC 01 router sabse pehle hai). Ek waqt '
    'mein sirf ek workflow change karein aur turant test karein. Merge na karein - alag workflows '
    'isliye hain taaki ek service ka fix doosri service ko tod na sake.'))

story.append(heading('10.3 Common Issues & Fixes', 1))
story += make_table(
    ['Problem', 'Likely Cause', 'Fix'],
    [
        ['Customer ko reply nahi aa raha', 'Token expire / webhook unsubscribed', 'Meta dashboard check, naya token Settings me dalo'],
        ['Payment aaya but status PAID nahi', 'Webhook secret mismatch', 'RAZORPAY_WEBHOOK_SECRET dono jagah same rakho'],
        ['Reminders nahi ja rahe', 'Template approved nahi / quiet hours', 'Meta templates check, REMINDER_QUIET config dekho'],
        ['Portal login nahi ho raha', 'ADMIN_PASSWORD changed/env missing', '.env check karo, pm2 restart csc-portal'],
        ['n8n OOM / slow', '2GB kam pad raha', 'Swap add karo ya 4GB VPS upgrade'],
        ['Executions me red errors', 'Data table name changed', 'Error log kholo, node input dekho'],
    ],
    [0.30, 0.32, 0.38], caption='Table 11: Troubleshooting quick reference')
story.append(Spacer(1, 10))
story.append(P(
    'Is guide ke saath aapke paas poora launch kit hai: server setup commands, database restore '
    'steps, WhatsApp aur payment production credentials ka setup, portal deployment, testing '
    'checklist aur maintenance routine. Launch ke baad pehle mahine specifically dhyan rakhein '
    'ki customers ka experience smooth ho - bot ki language simple Hinglish mein hai, validation '
    'errors helpful hain, aur reminder limits anti-harassment ke saath tuned hain. Jab volume '
    'badhe, naye services add karna sirf database rows ka kaam hai - koi naya workflow nahi '
    'banana padega.'))

doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('Body PDF generated:', OUT)
print('Pages:', doc.page)
